config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  resources :home do
    member do
      get 'results'
      get 'offering'
    end
  end

  resources :activities
  resources :categories
  resources :offerings
  resources :providers
  resources :reservations
  resources :trips

  namespace :admin do
    root 'application#index'

    resources :activities, only: [:new, :create, :edit, :update, :destroy]
    resources :categories, only: [:new, :create, :edit, :update, :destroy]
    resources :offerings, only: [:new, :create, :edit, :update, :destroy]
    resources :providers, only: [:new, :create, :edit, :update, :destroy]
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
    resources :trips, only: [:new, :create, :edit, :update, :destroy]
  end

  devise_for :users

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :offerings, dependent: :delete_all

  validates :description, presence: true, length: {maximum: 1000}
  validates :name, presence: true
  validates :categories, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :offering
  mount_uploader :file, AttachmentUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :activities, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true
end

app/models/offering.rb
class Offering < ApplicationRecord
  belongs_to :provider
  belongs_to :activity
  has_many :reservations
  has_many :attachments, dependent: :destroy

  has_attached_file :feature_picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  validates :description, presence: true, length: { maximum: 1000 }
  validates :place, presence: true
  validates :pricingperperson, presence: true
  validates :inclusions, presence: true
  validates :exclusions, presence: true

end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :offerings, dependent: :delete_all

  validates :name, presence: true
  validates :email_1, presence: true
  validates :email_2, presence: true
  validates :phone_1, presence: true
  validates :phone_2, presence: true
  validates :tax_number, presence: true
  validates :street_number, presence: true
  validates :street_name_1, presence: true
  validates :city, presence: true
  validates :province, presence: true
  validates :country, presence: true
  validates :website, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :trip
  belongs_to :offering

  validates :booking_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :user_id, presence: true
  validates :offering, presence: true
  validates :status, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :delete_all

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user_id, presence: true
  validates :number_of_adults, presence: true
  validates :number_of_infants, presence: true
  validates :number_of_children, presence: true
  validates :city, presence: true
  validates :region, presence: true
  validates :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
    @offerings = Offering.first(6)
  end

  def results
    @offerings = Offering.all
  end

  def offering
    @offerings = Offering.find(7)
  end

  private

  def admins_and_users
    !current_user.nil? ? 'application' : 'home'
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :authenticate_user!
  layout :layout_by_resource
  def index
    @providers = Provider.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @provider = Provider.find(params[:id])
  end

  def show
    @provider = Provider.find(params[:id])
  end

  private

  def provider_params
    params.require(:provider).permit(:name, :email_1, :email_2, :phone_1,
                                     :phone_2, :tax_number, :street_number,
                                     :street_name_1, :city, :province,
                                     :country, :website)
  end

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Matopo").join(" - ")
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/providers/_form.html.erb
<%= simple_form_for(@provider) do |f| %>
  <%= f.input :name %>
  <%= f.input :email_1 %>
  <%= f.input :email_2 %>
  <%= f.input :phone_1 %>
  <%= f.input :phone_2 %>
  <%= f.input :tax_number %>
  <%= f.input :street_number %>
  <%= f.input :street_name_1 %>
  <%= f.input :city %>
  <%= f.input :province %>
  <%= f.input :country %>
  <%= f.input :website %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/providers/index.html.erb
<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
      <%= link_to "New Provider", new_admin_provider_path, class: "btn btn-primary" %>
    </div>
  </div>
  <h2>Providers</h2>
</div>

<center>
  <div class="pagination">
    <%= will_paginate @providers %>
  </div>
</center>
<div id="providers">
  <centre>
    <div class="table-responsive table-striped table-condensed">
      <table class="table table-responsive table-striped table-condensed">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email Address</th>
            <th>Cellphone</th>
            <th>Tax Number</th>
            <th>Street Number</th>
            <th>Street Name</th>
            <th>City</th>
            <th>Country</th>
            <th>Website</th>
            <th>Manipulation</th>
          </tr>
        </thead>

        <tbody>
          <% @providers.each do |provider| %>
          <tr>
            <td>
              <p><%=  provider.id %></p>
            </td>
            <td>
              <p><%=  provider.name %></p>
            </td>
            <td>
              <p><%=  provider.email_1 %></p>
            </td>
            <td>
              <p><%=  provider.phone_1 %></p>
            </td>
            <td>
              <p><%=  provider.tax_number %></p>
            </td>
            <td>
              <p><%=  provider.street_number %></p>
            </td>
            <td>
              <p><%=  provider.street_name_1 %></p>
            </td>
            <td>
              <p><%=  provider.city %></p>
            </td>
            <td>
              <p><%=  provider.country %></p>
            </td>
            <td>
              <p><%=  provider.website %></p>
            </td>

            <td>
              <div class="pull-right hidden-phone">

                <%= link_to  admin_provider_path(provider), class: "btn btn-success btn-xs" do %>
                <i class=" fa fa-check"></i>
                <%end%>

                <%= link_to  edit_admin_provider_path(provider), class: "btn btn-primary btn-xs" do %>
                <i class=" fa fa-pencil"></i>
                <%end%>

                <%= link_to admin_provider_path(provider), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure you want to delete this provider?" } do %>
                <i class=" fa fa-trash-o"></i>
                <%end%>

              </div>

            </td>
          </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </centre>

</div>

app/views/providers/show.html.erb
<header>
  <h3>Provider:
    <%= @provider.name %></h3>
</header>

<p>
  <b>Name:&nbsp;</b>
  <%=@provider.name%>
</p>
<p>
  <b>Email:&nbsp;</b>
  <%=@provider.email_1%>
</p>
<p>
  <b>Alternative Email:&nbsp;</b>
  <%= @provider.email_2%></p>
<p>
  <b>Phone:&nbsp;</b>
  <%= @provider.phone_1%>
</p>
<p>
   <b>Phone 2:&nbsp;</b>
   <%= @provider.phone_2  %>
 </p>
<p>
  <b>Tax Number:&nbsp;</b>
  <%= @provider.tax_number %>
</p>
<p>
  <b>Street Number:&nbsp;</b>
  <%= @provider.street_number  %>
</p>
<p>
  <b>Street Number:&nbsp;</b>
  <%= @provider.street_name_1  %>
</p>
<p>
  <b>City:&nbsp;</b>
  <%= @provider.city  %>
</p>
<p>
  <b>Province:&nbsp;</b>
  <%= @provider.province  %>
</p>
<p>
  <b>Country:&nbsp;</b>
  <%= @provider.country  %>
</p>
<p>
  <b>Website:&nbsp;</b>
  <%= @provider.website  %>
</p>

<ul class="actions">
  <li>
    <%= link_to "Edit Provider", [:edit, @provider], class: "edit" %>
  </li>
  <li>
    <%= link_to "Delete Provider", [@provider],
        method: :delete,
        data: { confirm: "Are you sure you want to delete this provider?" },
        class: "delete"
    %>
  </li>
</ul>