config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  resources :home do
    member do
      get 'results'
      get 'offering'
    end
  end

  resources :activities
  resources :categories
  resources :offerings
  resources :providers
  resources :reservations
  resources :trips

  namespace :admin do
    root 'application#index'

    resources :activities, only: [:new, :create, :edit, :update, :destroy]
    resources :categories, only: [:new, :create, :edit, :update, :destroy]
    resources :offerings, only: [:new, :create, :edit, :update, :destroy]
    resources :providers, only: [:new, :create, :edit, :update, :destroy]
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
    resources :trips, only: [:new, :create, :edit, :update, :destroy]
  end

  devise_for :users

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :offerings, dependent: :delete_all

  validates :description, presence: true, length: {maximum: 1000}
  validates :name, presence: true
  validates :categories, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :offering
  mount_uploader :file, AttachmentUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :activities, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true
end

app/models/offering.rb
class Offering < ApplicationRecord
  belongs_to :provider
  belongs_to :activity
  has_many :reservations
  has_many :attachments, dependent: :destroy

  has_attached_file :feature_picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  validates :description, presence: true, length: { maximum: 1000 }
  validates :place, presence: true
  validates :pricingperperson, presence: true
  validates :inclusions, presence: true
  validates :exclusions, presence: true

end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :offerings, dependent: :delete_all

  validates :name, presence: true
  validates :email_1, presence: true
  validates :email_2, presence: true
  validates :phone_1, presence: true
  validates :phone_2, presence: true
  validates :tax_number, presence: true
  validates :street_number, presence: true
  validates :street_name_1, presence: true
  validates :city, presence: true
  validates :province, presence: true
  validates :country, presence: true
  validates :website, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :trip
  belongs_to :offering

  validates :booking_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :user_id, presence: true
  validates :offering, presence: true
  validates :status, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :delete_all

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user_id, presence: true
  validates :number_of_adults, presence: true
  validates :number_of_infants, presence: true
  validates :number_of_children, presence: true
  validates :city, presence: true
  validates :region, presence: true
  validates :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_category, only: [:create]
  before_action :set_activity, only: %i[show edit update destroy]
  before_action :authenticate_user!
  layout :layout_by_resource

  def index
    @activities = Activity.paginate(page: params[:page], per_page: 10)
  end

  def show; end

  private

  def activity_params
    params.require(:activity).permit(:name,
                                     :description,
                                     category_ids: [])
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_category
    @category = Category.new
  end

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < Admin::ApplicationController
  before_action :set_category, only: [:create]
  before_action :set_activity, only: %i[show edit update destroy]
  layout :layout_by_resource

  def new
    @activity = Activity.new
  end

  def create
    @activity = @category.activities.build(activity_params)
    if @activity.save
      flash[:notice] = 'Activity has been created.'
      redirect_to activity_path(@activity)
    else
      flash.now[:alert] = 'Activity has not been created.'
      render 'new'
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    if @activity.update(activity_params)
      flash[:notice] = 'Activity has been updated.'
      redirect_to [@category, @activity]
    else
      flash.now[:alert] = 'Activity has not been updated.'
      render 'edit'
    end
  end

  def destroy
    if @activity.destroy
      flash[:notice] = 'Activity has been deleted.'
      redirect_to @activity
    else
      flash.now[:alert] = 'Activity has not been deleted.'
      redirect_to activities_path
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name,
                                     :description,
                                     category_ids: [])
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_category
    @category = Category.new
  end

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
    @offerings = Offering.first(6)
  end

  def results
    @offerings = Offering.all
  end

  def offering
    @offerings = Offering.find(7)
  end

  private

  def admins_and_users
    !current_user.nil? ? 'application' : 'home'
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Matopo").join(" - ")
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for @activity do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :categories %>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/activities/index.html.erb
<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
      <%= link_to "New Activity", new_admin_activity_path, class: "btn btn-primary" %>
    </div>
  </div>
  <h2>Activities</h2>
</div>

<center>
  <div class="pagination">
    <%= will_paginate @activities %>
  </div>
</center>

<div id="activities">
  <centre>
    <div class="table-responsive table-striped table-condensed">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Categories</th>
            <th>Manipulation</th>
          </tr>
        </thead>

        <tbody>
          <% @activities.each do |activity| %>
          <tr>
            <td>
              <p><%=  activity.id %></p>
            </td>
            <td>
              <p><%=  activity.name %></p>
            </td>
            <td>
            <% activity.categories.each do |category| %>
              <%=  category.name %> &nbsp
            <% end%>
          </td>
            <td>
              <p><%=  activity.description %></p>
            </td>

            <td>
                <%= link_to  activity_path(activity), class: "btn btn-success btn-xs" do %>
                <i class=" fa fa-check"></i>
                <%end%>

                <%= link_to  edit_admin_activity_path(activity), class: "btn btn-primary btn-xs" do %>
                <i class=" fa fa-pencil"></i>
                <%end%>

                <%= link_to activity_path(activity), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure you want to delete this provider?" } do %>
                <i class=" fa fa-trash-o"></i>
                <%end%>
            </td>
          </tr>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</centre>

</div>

app/views/activities/show.html.erb
<header>
  <h3><b>Name:&nbsp;</b><%= @activity.name %></h3>
</header>

<p><b>Description:&nbsp;</b><%= @activity.description %></p>
<p><b>Categories:&nbsp;</b>
<ul>
  <% @activity.categories.each do |category| %>
    <li><%=  category.name %></li>
  <% end%>
</ul>

<ul class="actions">
    <li>
      <li><%= link_to "Edit Activity",
              edit_admin_activity_path(@activity),
              class: "edit" %>
    </li>
    <li>
        <%= link_to "Delete Activity", admin_activity_path(@activity),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this activity?" },
            class: "delete"
        %>
    </li>
</ul>